projects:
  chat-app:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: pwovm5zkjjh57lcxd7wqxi5hem
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://xsi7xwwftnf4tjgu53o7bh74gi.appsync-api.us-east-1.amazonaws.com/graphql
